// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission12.Models;

namespace Mission12.Migrations
{
    [DbContext(typeof(GroupContext))]
    [Migration("20220321225213_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.23");

            modelBuilder.Entity("Mission12.Models.Appointment", b =>
                {
                    b.Property<int>("AppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Booked")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("AppointmentId");

                    b.HasIndex("GroupId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            AppointmentId = 1,
                            Booked = true,
                            Description = "Morning",
                            EndDate = new DateTime(2022, 5, 3, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            GroupId = 1,
                            StartDate = new DateTime(2022, 5, 3, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 2,
                            Booked = true,
                            Description = "Mid Morning",
                            EndDate = new DateTime(2022, 5, 3, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            GroupId = 2,
                            StartDate = new DateTime(2022, 5, 3, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 3,
                            Booked = true,
                            Description = "Late Morning",
                            EndDate = new DateTime(2022, 5, 3, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            GroupId = 3,
                            StartDate = new DateTime(2022, 5, 3, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 4,
                            Booked = false,
                            Description = "Afternoon",
                            EndDate = new DateTime(2022, 5, 3, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 3, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 5,
                            Booked = false,
                            Description = "Mid Afternoon",
                            EndDate = new DateTime(2022, 5, 3, 13, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 3, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 6,
                            Booked = false,
                            Description = "Late Afternoon",
                            EndDate = new DateTime(2022, 5, 3, 14, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 3, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 7,
                            Booked = false,
                            Description = "Evening",
                            EndDate = new DateTime(2022, 5, 3, 17, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 3, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 8,
                            Booked = false,
                            Description = "Mid Evening",
                            EndDate = new DateTime(2022, 5, 3, 18, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 3, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 9,
                            Booked = false,
                            Description = "Late Evening",
                            EndDate = new DateTime(2022, 5, 3, 19, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 3, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 10,
                            Booked = false,
                            Description = "Morning",
                            EndDate = new DateTime(2022, 5, 4, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 4, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 11,
                            Booked = false,
                            Description = "Mid Morning",
                            EndDate = new DateTime(2022, 5, 4, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 4, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 12,
                            Booked = false,
                            Description = "Late Morning",
                            EndDate = new DateTime(2022, 5, 4, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 4, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 13,
                            Booked = false,
                            Description = "Afternoon",
                            EndDate = new DateTime(2022, 5, 4, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 4, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 14,
                            Booked = false,
                            Description = "Mid Afternoon",
                            EndDate = new DateTime(2022, 5, 4, 13, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 4, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 15,
                            Booked = false,
                            Description = "Late Afternoon",
                            EndDate = new DateTime(2022, 5, 4, 14, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 4, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 16,
                            Booked = false,
                            Description = "Evening",
                            EndDate = new DateTime(2022, 5, 4, 17, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 4, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 17,
                            Booked = false,
                            Description = "Mid Evening",
                            EndDate = new DateTime(2022, 5, 4, 18, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 4, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 18,
                            Booked = false,
                            Description = "Late Evening",
                            EndDate = new DateTime(2022, 5, 4, 19, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 4, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 19,
                            Booked = false,
                            Description = "Morning",
                            EndDate = new DateTime(2022, 5, 5, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 5, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 20,
                            Booked = false,
                            Description = "Mid Morning",
                            EndDate = new DateTime(2022, 5, 5, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 5, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 21,
                            Booked = false,
                            Description = "Late Morning",
                            EndDate = new DateTime(2022, 5, 5, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 5, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 22,
                            Booked = false,
                            Description = "Afternoon",
                            EndDate = new DateTime(2022, 5, 5, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 5, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 23,
                            Booked = false,
                            Description = "Mid Afternoon",
                            EndDate = new DateTime(2022, 5, 5, 13, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 5, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 24,
                            Booked = false,
                            Description = "Late Afternoon",
                            EndDate = new DateTime(2022, 5, 5, 14, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 5, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 25,
                            Booked = false,
                            Description = "Evening",
                            EndDate = new DateTime(2022, 5, 5, 17, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 5, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 26,
                            Booked = false,
                            Description = "Mid Evening",
                            EndDate = new DateTime(2022, 5, 5, 18, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 5, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 27,
                            Booked = false,
                            Description = "Late Evening",
                            EndDate = new DateTime(2022, 5, 5, 19, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 5, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 28,
                            Booked = false,
                            Description = "Morning",
                            EndDate = new DateTime(2022, 5, 6, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 6, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 29,
                            Booked = false,
                            Description = "Mid Morning",
                            EndDate = new DateTime(2022, 5, 6, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 6, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 30,
                            Booked = false,
                            Description = "Late Morning",
                            EndDate = new DateTime(2022, 5, 6, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 6, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 31,
                            Booked = false,
                            Description = "Afternoon",
                            EndDate = new DateTime(2022, 5, 6, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 6, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 32,
                            Booked = false,
                            Description = "Mid Afternoon",
                            EndDate = new DateTime(2022, 5, 6, 13, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 6, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 33,
                            Booked = false,
                            Description = "Late Afternoon",
                            EndDate = new DateTime(2022, 5, 6, 14, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 6, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 34,
                            Booked = false,
                            Description = "Evening",
                            EndDate = new DateTime(2022, 5, 6, 17, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 6, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 35,
                            Booked = false,
                            Description = "Mid Evening",
                            EndDate = new DateTime(2022, 5, 6, 18, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 6, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 36,
                            Booked = false,
                            Description = "Late Evening",
                            EndDate = new DateTime(2022, 5, 6, 19, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 6, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 37,
                            Booked = false,
                            Description = "Morning",
                            EndDate = new DateTime(2022, 5, 7, 8, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 7, 8, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 38,
                            Booked = false,
                            Description = "Mid Morning",
                            EndDate = new DateTime(2022, 5, 7, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 7, 9, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 39,
                            Booked = false,
                            Description = "Late Morning",
                            EndDate = new DateTime(2022, 5, 7, 10, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 7, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 40,
                            Booked = false,
                            Description = "Afternoon",
                            EndDate = new DateTime(2022, 5, 7, 12, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 7, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 41,
                            Booked = false,
                            Description = "Mid Afternoon",
                            EndDate = new DateTime(2022, 5, 7, 13, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 7, 13, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 42,
                            Booked = false,
                            Description = "Late Afternoon",
                            EndDate = new DateTime(2022, 5, 7, 14, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 7, 14, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 43,
                            Booked = false,
                            Description = "Evening",
                            EndDate = new DateTime(2022, 5, 7, 17, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 7, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 44,
                            Booked = false,
                            Description = "Mid Evening",
                            EndDate = new DateTime(2022, 5, 7, 18, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 7, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AppointmentId = 45,
                            Booked = false,
                            Description = "Late Evening",
                            EndDate = new DateTime(2022, 5, 7, 19, 45, 0, 0, DateTimeKind.Unspecified),
                            StartDate = new DateTime(2022, 5, 7, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Mission12.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("GroupSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");

                    b.HasData(
                        new
                        {
                            GroupId = 1,
                            Email = "codytest@gmail.com",
                            GroupName = "Carlock",
                            GroupSize = 2,
                            Phone = "253-555-5555"
                        },
                        new
                        {
                            GroupId = 2,
                            Email = "provotest@gmail.com",
                            GroupName = "Provo 6",
                            GroupSize = 15,
                            Phone = "801-555-5555"
                        },
                        new
                        {
                            GroupId = 3,
                            Email = "ysatest@gmail.com",
                            GroupName = "YSA 128",
                            GroupSize = 3,
                            Phone = "911-555-5555"
                        });
                });

            modelBuilder.Entity("Mission12.Models.Appointment", b =>
                {
                    b.HasOne("Mission12.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");
                });
#pragma warning restore 612, 618
        }
    }
}
